### ISSUE TITLE
Ignore node_modules

### ISSUE THREAD

**Issue by GauravWalia19** [TechOUs/Profile-Builder#21]
**Describe the bug**
Node modules adds extra space in repo and is unncessary folder for this repo.

**To Reproduce**
1. Go to '.gitignore' file
2. Ignore node_modules
3. Delete node_modules

**Expected behavior**
Having clean project structure.

**Desktop (please complete the following information):**
 - OS: LINUX
 - Browser chrome
 - Version 75

**Additional context**

**Comment by anarchymonkey** [comment]
Thank you for the suggestion, will see to it.

**Comment by GauravWalia19** [comment]
Don't close issue until it fixed.
